name: 'Release Startup'
description: 'Release Startup GitHub Action'
author: 'Rojan Gh.'
inputs:
  stage:
    required: true
    description: 'Target stage'
  reference:
    required: false
    description: 'Git reference'
    default: ''
  hotfix:
    required: false
    description: 'If it is a hotfix'
    default: "false"
outputs:
  reference:
    description: 'Git reference'
  version:
    description: 'Release version'
  previousVersion:
    description: 'Previous release version'
runs:
  using: 'node16'
  main: 'dist/index.js'
