name: Publish

on:
  pull_request:
    types:
      - closed

jobs:
  #publish:
  #  uses: NoorDigitalAgency/.github/.github/workflows/publish-action.yaml@main
  #  with:
  #    branch: main
  #  secrets:
  #    token: ${{ secrets.ACTIONS_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
